### ISSUE TITLE
secrets.CLOUDFLARE_API_TOKEN 和 secrets.CF_API_TOKEN 这两个是否有区别？

### ISSUE THREAD

**Issue by Jesn** [cwxiaos/bark-worker#16]
```
name: Deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
  
env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}


      - name: Deploy worker
        uses: cloudflare/wrangler-action@v3.7.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: "deploy"
          wranglerVersion: "3.77.0"
```
